import Foundation

/// Weekly therapy report generated by Gemma — summarises panic episodes,
/// identified patterns, and sleep data. User can review and edit before sharing.
struct TherapyReport: Identifiable, Codable {

    let id: UUID
    let weekStart: Date
    let weekEnd: Date
    let episodeCount: Int
    let totalDurationMinutes: Double
    let dominantPatterns: [String]
    let episodeDates: [Date]
    let averageSleepHours: Double?
    var gemmaReportBody: String
    let createdAt: Date
    var isShared: Bool

    init(
        id: UUID = UUID(),
        weekStart: Date,
        weekEnd: Date,
        episodeCount: Int,
        totalDurationMinutes: Double,
        dominantPatterns: [String] = [],
        episodeDates: [Date] = [],
        averageSleepHours: Double? = nil,
        gemmaReportBody: String,
        createdAt: Date = Date(),
        isShared: Bool = false
    ) {
        self.id = id
        self.weekStart = weekStart
        self.weekEnd = weekEnd
        self.episodeCount = episodeCount
        self.totalDurationMinutes = totalDurationMinutes
        self.dominantPatterns = dominantPatterns
        self.episodeDates = episodeDates
        self.averageSleepHours = averageSleepHours
        self.gemmaReportBody = gemmaReportBody
        self.createdAt = createdAt
        self.isShared = isShared
    }
}

// MARK: - Computed Properties

extension TherapyReport {
    /// Formatted date range for display, e.g. "May 4 – May 10, 2026".
    var formattedDateRange: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d"
        let start = formatter.string(from: weekStart)
        formatter.dateFormat = "MMM d, yyyy"
        let end = formatter.string(from: weekEnd)
        return "\(start) – \(end)"
    }

    /// Average episode duration in minutes, rounded to one decimal place.
    var averageEpisodeDurationMinutes: Double? {
        guard episodeCount > 0 else { return nil }
        return totalDurationMinutes / Double(episodeCount)
    }
}
